services:
  - type: web
    name: dietitian-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DIETITIAN.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DIETITIAN.settings
      - key: SECRET_KEY
        generateValue: true
